-- Ported from BarrelConnect migration 082_crhsr_seed_schools.sql
-- Adapted for breakawayroping-mobile-app (barrel-specific columns removed).
-- Idempotent; safe to re-run. Runs AFTER breakaway base migrations 001-007.

-- CR/HSR seed data from validated research files
-- Source: /home/ubuntu/college_rodeo_schools.json, /home/ubuntu/high_school_rodeo_schools.json

INSERT INTO public.schools (
  name,
  type,
  colors,
  mascot,
  region,
  association,
  state,
  city,
  country,
  source
)
VALUES
  ('Panola College', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Carthage', 'US', 'seed_docx'),
  ('Hill College', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Hillsboro', 'US', 'seed_docx'),
  ('Weatherford College', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Weatherford', 'US', 'seed_docx'),
  ('Vernon College', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Vernon', 'US', 'seed_docx'),
  ('Tarleton State University', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Stephenville', 'US', 'seed_docx'),
  ('Sam Houston State University', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Huntsville', 'US', 'seed_docx'),
  ('McNeese State University', 'college', NULL, NULL, NULL, 'NIRA', 'LA', 'Lake Charles', 'US', 'seed_docx'),
  ('Louisiana State University', 'college', NULL, NULL, NULL, 'NIRA', 'LA', 'Baton Rouge', 'US', 'seed_docx'),
  ('Pearl River Community College', 'college', NULL, NULL, NULL, 'NIRA', 'MS', 'Poplarville', 'US', 'seed_docx'),
  ('Northeast Texas Community College', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Mount Pleasant', 'US', 'seed_docx'),
  ('Trinity Valley Community College', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Athens', 'US', 'seed_docx'),
  ('Ranger College', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Ranger', 'US', 'seed_docx'),
  ('Wharton County Junior College', 'college', NULL, NULL, NULL, 'NIRA', 'TX', 'Wharton', 'US', 'seed_docx'),
  ('Alabama High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'AL', NULL, 'US', 'seed_docx'),
  ('Alaska High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'AK', NULL, 'US', 'seed_docx'),
  ('Arizona High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'AZ', NULL, 'US', 'seed_docx'),
  ('Arkansas High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'AR', NULL, 'US', 'seed_docx'),
  ('California High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'CA', NULL, 'US', 'seed_docx'),
  ('Colorado High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'CO', NULL, 'US', 'seed_docx'),
  ('Connecticut High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'CT', NULL, 'US', 'seed_docx'),
  ('Delaware High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'DE', NULL, 'US', 'seed_docx'),
  ('Florida High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'FL', NULL, 'US', 'seed_docx'),
  ('Georgia High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'GA', NULL, 'US', 'seed_docx'),
  ('Hawaii High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'HI', NULL, 'US', 'seed_docx'),
  ('Idaho High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'ID', NULL, 'US', 'seed_docx'),
  ('Illinois High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'IL', NULL, 'US', 'seed_docx'),
  ('Indiana High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'IN', NULL, 'US', 'seed_docx'),
  ('Iowa High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'IA', NULL, 'US', 'seed_docx'),
  ('Kansas High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'KS', NULL, 'US', 'seed_docx'),
  ('Kentucky High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'KY', NULL, 'US', 'seed_docx'),
  ('Louisiana High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'LA', NULL, 'US', 'seed_docx'),
  ('Maine High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'ME', NULL, 'US', 'seed_docx'),
  ('Maryland High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'MD', NULL, 'US', 'seed_docx'),
  ('Massachusetts High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'MA', NULL, 'US', 'seed_docx'),
  ('Michigan High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'MI', NULL, 'US', 'seed_docx'),
  ('Minnesota High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'MN', NULL, 'US', 'seed_docx'),
  ('Mississippi High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'MS', NULL, 'US', 'seed_docx'),
  ('Missouri High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'MO', NULL, 'US', 'seed_docx'),
  ('Montana High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'MT', NULL, 'US', 'seed_docx'),
  ('Nebraska High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'NE', NULL, 'US', 'seed_docx'),
  ('Nevada High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'NV', NULL, 'US', 'seed_docx'),
  ('New Hampshire High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'NH', NULL, 'US', 'seed_docx'),
  ('New Jersey High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'NJ', NULL, 'US', 'seed_docx'),
  ('New Mexico High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'NM', NULL, 'US', 'seed_docx'),
  ('New York High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'NY', NULL, 'US', 'seed_docx'),
  ('North Carolina High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'NC', NULL, 'US', 'seed_docx'),
  ('North Dakota High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'ND', NULL, 'US', 'seed_docx'),
  ('Ohio High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'OH', NULL, 'US', 'seed_docx'),
  ('Oklahoma High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'OK', NULL, 'US', 'seed_docx'),
  ('Oregon High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'OR', NULL, 'US', 'seed_docx'),
  ('Pennsylvania High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'PA', NULL, 'US', 'seed_docx'),
  ('Rhode Island High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'RI', NULL, 'US', 'seed_docx'),
  ('South Carolina High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'SC', NULL, 'US', 'seed_docx'),
  ('South Dakota High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'SD', NULL, 'US', 'seed_docx'),
  ('Tennessee High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'TN', NULL, 'US', 'seed_docx'),
  ('Texas High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'TX', NULL, 'US', 'seed_docx'),
  ('Utah High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'UT', NULL, 'US', 'seed_docx'),
  ('Vermont High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'VT', NULL, 'US', 'seed_docx'),
  ('Virginia High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'VA', NULL, 'US', 'seed_docx'),
  ('Washington High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'WA', NULL, 'US', 'seed_docx'),
  ('West Virginia High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'WV', NULL, 'US', 'seed_docx'),
  ('Wisconsin High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'WI', NULL, 'US', 'seed_docx'),
  ('Wyoming High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'WY', NULL, 'US', 'seed_docx'),
  ('Alberta High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'AB', NULL, 'CA', 'seed_docx'),
  ('British Columbia High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'BC', NULL, 'CA', 'seed_docx'),
  ('Manitoba High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'MB', NULL, 'CA', 'seed_docx'),
  ('Saskatchewan High School Rodeo Association', 'high_school', NULL, NULL, NULL, 'NHSRA', 'SK', NULL, 'CA', 'seed_docx')
ON CONFLICT (name, type, state) DO UPDATE SET
  association = EXCLUDED.association,
  city = EXCLUDED.city,
  country = EXCLUDED.country,
  source = EXCLUDED.source,
  updated_at = now();
